# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  API_URL: https://ip5-backend.azurewebsites.net

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    pushd frontend
    npm install
    npm run build
    popd
  displayName: 'build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './frontend/dist'
    ArtifactName: 'frontend'
    publishLocation: 'Container'