trigger:
  branches:
    include:
      - master
  paths:
    include:
      - frontend/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  API_URL: https://ip5-backend.azurewebsites.net
  NODE_ENV: production

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      pushd frontend
      yarn install
      yarn run build
      popd
    displayName: 'build'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: './frontend/dist'
      ArtifactName: 'frontend'
      publishLocation: 'Container'